// Environment Configuration
// This file can be dynamically generated by your build process or server
// to inject environment-specific variables

window.MSA_ENV = {
  // API Configuration from environment variables
  // Set these values to override the default API configuration
  API_URL: 'http://localhost:8080', // e.g., "https://api.utmmsa.com" or "http://localhost:8080"
  API_KEY: undefined, // e.g., "your-bot-api-key" (only needed for bot operations)
  
  // Environment info
  ENVIRONMENT: 'production', // 'development', 'staging', 'production'
  VERSION: '2025.8.1',     // Application version
  BUILD_TIME: undefined,  // Build timestamp
  
  // Feature flags from environment
  ENABLE_DEBUG: true,
  ENABLE_ANALYTICS: false
};

// Example: To set a custom API URL (e.g., ngrok tunnel), uncomment and modify this line:
// window.MSA_ENV.API_URL = "https://your-ngrok-url.ngrok-free.app";

// Example: To set the bot API key for bot-authenticated operations, uncomment and modify:
// window.MSA_ENV.API_KEY = "your-secret-bot-api-key";

// Development helper - logs configuration in development
if (window.location.hostname === 'localhost') {
  console.log('🔧 MSA Environment Config Loaded', window.MSA_ENV);
  console.log('📡 Current API URL will be determined by config.js');
}
